spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=ecommerceapp
spring.datasource.password=ecommerceapp

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.rest.base-path=/api

# used in CORS configuration, can be a comma-separated list of origins
allowed.origins=http://localhost:4200

# ALL - Exposes all Spring Data repositories regardless of their Java visibility or annotation configuration
# DEFAULT - Exposes public Spring Data repositories or ones explicitly annotated with @RepositoryRestResource and its exported attribute not set to false
# VISIBILITY - Exposes only public Spring Data repositories regardless of annotation configuration
# ANNOTATED - Exposes only Spring Data repositories explicitly annotated with @RepositoryRestResource and its exported attribute not set to false (default is true)
spring.data.rest.detection-strategy=ANNOTATED